<? php
echo '';
echo '<!DOCTYPE html>';
echo '';
echo '<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">';
echo '';
echo '<head>';
echo '<script src="https://cdn.optimizely.com/js/8358352250.js"></script>';
echo '';
echo '<!-- Google Analytics Content Experiment code -->';
echo '<script>function utmx_section(){}function utmx(){}(function(){var';
echo 'k='134353429-7',d=document,l=d.location,c=d.cookie;';
echo 'if(l.search.indexOf('utm_expid='+k)>0)return;';
echo 'function f(n){if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.';
echo 'indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.';
echo 'length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;d.write(';
echo ''<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':';
echo ''://www')+'.google-analytics.com/ga_exp.js?'+'utmxkey='+k+';
echo ''&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().';
echo 'valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+';
echo ''" type="text/javascript" charset="utf-8"><\/sc'+'ript>')})();';
echo '</script><script>utmx('url','A/B');</script>';
echo '<!-- End of Google Analytics Content Experiment code -->';
echo '<style>';
echo '#root header {';
echo 'min-height: auto;';
echo '}';
echo '.hero-chatbot__container {';
echo 'overflow: visible !important;';
echo '}';
echo '.WebView-module__iframeWrapper__3QvWu {';
echo 'overflow-y: visible;';
echo '}';
echo '</style>';
echo '';
echo '<meta charset="utf-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">';
echo '';
echo '<!-- BEGIN SEOmatic rendered SEO Meta -->';
echo '';
echo '<title>Online Doctor Consultations &amp; Advice | babylon health</title>';
echo '';
echo '<!-- Standard SEO -->';
echo '';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<meta name="referrer" content="no-referrer-when-downgrade" />';
echo '<meta name="robots" content="all" />';
echo '<meta name="description" content="Book a doctors appointment in seconds and talk to a GP in minutes. Real time consultations via video/phone. Get medical advice online wherever you are." />';
echo '<meta name="generator" content="SEOmatic" />';
echo '<link rel="canonical" href="https://www.babylonhealth.com" />';
echo '<link rel="alternate" href="https://www.babylonhealth.com" hreflang="x-default" />';
echo '<meta name="geo.region" content="London" />';
echo '<meta name="geo.position" content="51.4927889,-0.1670012" />';
echo '<meta name="ICBM" content="51.4927889,-0.1670012" />';
echo '<meta name="geo.placename" content="Babylon Health" />';
echo '';
echo '<!-- Dublin Core basic info -->';
echo '';
echo '<meta name="dcterms.Identifier" content="https://www.babylonhealth.com" />';
echo '<meta name="dcterms.Format" content="text/html" />';
echo '<meta name="dcterms.Relation" content="babylon health" />';
echo '<meta name="dcterms.Language" content="en" />';
echo '<meta name="dcterms.Publisher" content="babylon health" />';
echo '<meta name="dcterms.Type" content="text/html" />';
echo '<meta name="dcterms.Coverage" content="https://www.babylonhealth.com/" />';
echo '<meta name="dcterms.Rights" content="Copyright &copy;2018 Babylon Health." />';
echo '<meta name="dcterms.Title" content="Online Doctor Consultations &amp; Advice" />';
echo '<meta name="dcterms.Subject" content="" />';
echo '<meta name="dcterms.Contributor" content="babylon health" />';
echo '<meta name="dcterms.Date" content="2018-03-02" />';
echo '<meta name="dcterms.Description" content="Book a doctors appointment in seconds and talk to a GP in minutes. Real time consultations via video/phone. Get medical advice online wherever you are." />';
echo '';
echo '<!-- Facebook OpenGraph -->';
echo '';
echo '<meta property="og:type" content="website" />';
echo '<meta property="og:locale" content="en_gb" />';
echo '<meta property="og:url" content="https://www.babylonhealth.com" />';
echo '<meta property="og:title" content="Online Doctor Consultations &amp; Advice | babylon health" />';
echo '<meta property="og:description" content="Book a doctors appointment in seconds and talk to a GP in minutes. Real time consultations via video/phone. Get medical advice online wherever you are." />';
echo '<meta property="og:image" content="https://www.babylonhealth.com/uploads/how-it-works/babylon-header-how-it-works-chatbot.jpg" />';
echo '<meta property="og:image:type" content="image/jpeg" />';
echo '<meta property="og:image:width" content="1607" />';
echo '<meta property="og:image:height" content="777" />';
echo '<meta property="og:site_name" content="babylon health" />';
echo '';
echo '';
echo '<!-- Humans.txt authorship http://humanstxt.org -->';
echo '';
echo '<link type="text/plain" rel="author" href="/humans.txt" />';
echo '';
echo '<!-- Domain verification -->';
echo '';
echo '';
echo '<!-- Identity -->';
echo '';
echo '<script type="application/ld+json">';
echo '{';
echo '"@context": "http://schema.org",';
echo '"@type": "Corporation",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '<!-- WebSite -->';
echo '';
echo '<script type="application/ld+json">';
echo '{';
echo '"@context": "http://schema.org",';
echo '"@type": "WebSite",';
echo '"name": "babylon health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"image": "https://www.babylonhealth.com/uploads/how-it-works/babylon-header-how-it-works-chatbot.jpg",';
echo '"copyrightHolder": {';
echo '"@type": "Corporation",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '},';
echo '"author": {';
echo '"@type": "Corporation",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '},';
echo '"creator": {';
echo '"@type": "Organization"';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '<!-- Place -->';
echo '';
echo '<script type="application/ld+json">';
echo '{';
echo '"@context": "http://schema.org",';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '<!-- Main Entity of Page -->';
echo '';
echo '<script type="application/ld+json">';
echo '{';
echo '"@context": "http://schema.org",';
echo '"@type": "WebPage",';
echo '"name": "Online Doctor Consultations &amp; Advice",';
echo '"description": "Book a doctors appointment in seconds and talk to a GP in minutes. Real time consultations via video/phone. Get medical advice online wherever you are.",';
echo '"image": {';
echo '"@type": "ImageObject",';
echo '"url": "https://www.babylonhealth.com/uploads/how-it-works/babylon-header-how-it-works-chatbot.jpg",';
echo '"width": "1607",';
echo '"height": "777"';
echo '},';
echo '"url": "https://www.babylonhealth.com",';
echo '"mainEntityOfPage": "https://www.babylonhealth.com",';
echo '"inLanguage": "en_gb",';
echo '"headline": "Online Doctor Consultations &amp; Advice",';
echo '"dateCreated": "2016-09-07T08:24:15+0000",';
echo '"dateModified": "2018-02-27T11:38:57+0000",';
echo '"datePublished": "2018-02-26T11:53:19+0000",';
echo '"copyrightYear": "2018",';
echo '"author": {';
echo '"@type": "Corporation",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '},';
echo '"copyrightHolder": {';
echo '"@type": "Corporation",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '},';
echo '"publisher": {';
echo '"@type": "Organization",';
echo '"name": "Babylon Health",';
echo '"url": "https://www.babylonhealth.com",';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '},';
echo '"location": {';
echo '"@type": "Place",';
echo '"name": "Babylon Health",';
echo '"hasMap": "http://maps.google.com/maps?q=Babylon+Health%2C+60+Sloane+Avenue%2C+Chelsea%2C+London+SW3+3DD%2C+London",';
echo '"url": "https://www.babylonhealth.com",';
echo '"geo": {';
echo '"@type": "GeoCoordinates",';
echo '"latitude": "51.4927889",';
echo '"longitude": "-0.1670012"';
echo '},';
echo '"address": {';
echo '"@type": "PostalAddress",';
echo '"streetAddress": "60 Sloane Avenue",';
echo '"addressLocality": "Chelsea",';
echo '"addressRegion": "London",';
echo '"postalCode": "SW3 3DD",';
echo '"addressCountry": "London"';
echo '}';
echo '}';
echo '},';
echo '"breadcrumb": {';
echo '"@type": "BreadcrumbList",';
echo '"itemListElement": [';
echo '{';
echo '"@type": "ListItem",';
echo '"position": "1",';
echo '"item": {';
echo '"@id": "https://www.babylonhealth.com",';
echo '"name": "Home"';
echo '}';
echo '}';
echo ']';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '<!-- Breadcrumbs -->';
echo '';
echo '<script type="application/ld+json">';
echo '{';
echo '"@context": "http://schema.org",';
echo '"@type": "BreadcrumbList",';
echo '"itemListElement": [';
echo '{';
echo '"@type": "ListItem",';
echo '"position": "1",';
echo '"item": {';
echo '"@id": "https://www.babylonhealth.com",';
echo '"name": "Home"';
echo '}';
echo '}';
echo ']';
echo '}';
echo '</script>';
echo '';
echo '<!-- Google Tag Manager -->';
echo '';
echo '';
echo '<!-- Google Analytics -->';
echo '';
echo '';
echo '<!-- END SEOmatic rendered SEO Meta -->';
echo '';
echo '<link rel="stylesheet" href="/assets/styles/main.css">';
echo '<link href="/assets/images/favicon.ico" type="image/x-icon" rel="shortcut icon">';
echo '';
echo '<!-- Facebook Pixel Code -->';
echo '<script>';
echo '!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?';
echo 'n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;';
echo 'n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;';
echo 't.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,';
echo 'document,'script','https://connect.facebook.net/en_US/fbevents.js');';
echo 'fbq('init', '425015857689174', {';
echo 'em: 'insert_email_variable,'';
echo '});';
echo 'fbq('track', 'PageView');';
echo '</script>';
echo '<noscript><img height="1" width="1" style="display:none"';
echo 'src="https://www.facebook.com/tr?id=425015857689174&ev=PageView&noscript=1"';
echo '/></noscript>';
echo '<!-- DO NOT MODIFY -->';
echo '<!-- End Facebook Pixel Code -->';
echo '<!-- Facebook Pixel Code Ireland -->';
echo '<script>';
echo '!function(f,b,e,v,n,t,s)';
echo '{if(f.fbq)return;n=f.fbq=function(){n.callMethod?';
echo 'n.callMethod.apply(n,arguments):n.queue.push(arguments)};';
echo 'if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';';
echo 'n.queue=[];t=b.createElement(e);t.async=!0;';
echo 't.src=v;s=b.getElementsByTagName(e)[0];';
echo 's.parentNode.insertBefore(t,s)}(window,document,'script',';
echo ''https://connect.facebook.net/en_US/fbevents.js');';
echo 'fbq('init', '1167415006639311');';
echo 'fbq('track', 'PageView');';
echo '</script>';
echo '<noscript>';
echo '<img height="1" width="1"';
echo 'src="https://www.facebook.com/tr?id=1167415006639311&ev=PageView';
echo '&noscript=1"/>';
echo '</noscript>';
echo '<!-- End Facebook Pixel Code -->';
echo '<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"5474914"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script><noscript><img src="//bat.bing.com/action/0?ti=5474914&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" /></noscript>';
echo '<meta name="google-site-verification" content="wfMaol4mosw72v0P63mcntdnwCVglWHn9QHHYiaRWzQ" />';
echo '<script type='application/ld+json'>{"@context": "http://www.schema.org","@type": "product","name": "babylon Dr App","aggregateRating":{"@type": "aggregateRating", "ratingValue": "4.76", "reviewCount": "16,644"}}</script>';
echo '<!-- start Google Analytics -->';
echo '<!-- Below is not JS Script -->';
echo '<script>';
echo '(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){';
echo '(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),';
echo 'm=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)';
echo '})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');';
echo '';
echo 'ga('create', 'UA-78074544-5', 'auto');';
echo 'ga('send', 'pageview');';
echo '</script>';
echo '<!-- end Google Analytics -->';
echo '<!-- Hotjar Tracking Code for www.babylonhealth.com -->';
echo '<script>';
echo '(function(h,o,t,j,a,r){';
echo 'h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};';
echo 'h._hjSettings={hjid:449668,hjsv:6};';
echo 'a=o.getElementsByTagName('head')[0];';
echo 'r=o.createElement('script');r.async=1;';
echo 'r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;';
echo 'a.appendChild(r);';
echo '})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');';
echo '</script>';
echo '';
echo '<script type="text/javascript">';
echo 'window.csrfTokenName = "CRAFT_CSRF_TOKEN";';
echo 'window.csrfTokenValue = "Fhg2SN0QdjJFNM8VQZbAhYPL2ex_QOf46TKfF43Q";';
echo '</script>';
echo '';
echo '<script src="/assets/scripts/app.js"></script>';
echo '';
echo '<script>document.cookie='resolution='+Math.max(screen.width,screen.height)+'; path=/';</script>';
echo '';
echo '<script>';
echo 'function getChatbotCookie(cname) {';
echo 'var name = cname + "=";';
echo 'var decodedCookie = decodeURIComponent(document.cookie);';
echo 'var ca = decodedCookie.split(';');';
echo 'for (var i = 0; i < ca.length; i++) {';
echo 'var c = ca[i];';
echo 'while (c.charAt(0) == ' ') {';
echo 'c = c.substring(1);';
echo '}';
echo 'if (c.indexOf(name) == 0) {';
echo 'return c.substring(name.length, c.length);';
echo '}';
echo '}';
echo 'return "";';
echo '}';
echo '';
echo 'function clearChatbotCookies() {';
echo 'const domain = ' domain=' + window.location.hostname.split('.').slice(-2).join('.') + ';';';
echo 'document.cookie = "authentication.api_key" + '=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;' + domain;';
echo 'document.cookie = "authentication.kong_api_key" + '=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;' + domain;';
echo 'document.cookie = "authentication.user_id" + '=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;' + domain;';
echo 'document.cookie = "authentication.access_token" + '=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;' + domain;';
echo '}';
echo '';
echo 'function triggerSignOutButton() {';
echo 'jQuery(SignInButton).text('Go online');';
echo '';
echo 'jQuery(';
echo ''<li id="RemoveMe" class="navigation__list__item all-devices"><a class="navigation__list__item__link" href="#">Sign out</a></li>'';
echo ').insertBefore(ListSignInButton).click(function(e) {';
echo 'e.preventDefault();';
echo 'jQuery(SignInButton).text('Sign in');';
echo 'jQuery(RemoveMe).remove();';
echo 'clearChatbotCookies();';
echo 'if (window.babylonChatbot && window.babylonChatbot.signOut) {';
echo 'window.babylonChatbot.signOut();';
echo '}';
echo '});';
echo '}';
echo '';
echo 'document.addEventListener("DOMContentLoaded", function (event) {';
echo 'if (';
echo 'getChatbotCookie("authentication.api_key")';
echo '&& getChatbotCookie("authentication.kong_api_key")';
echo '&& getChatbotCookie("authentication.user_id")';
echo '&& getChatbotCookie("authentication.access_token")';
echo ') {';
echo 'triggerSignOutButton()';
echo '} else {';
echo 'window.triggerSignOutButton = triggerSignOutButton';
echo '}';
echo '})';
echo '</script>';
echo '</head>';
echo '';
echo '<body>';
echo '<!-- Google Code for Registrations (Desktop) Conversion Page -->';
echo '<script type="text/javascript">';
echo '/* <![CDATA[ */';
echo 'var google_conversion_id = 945990079;';
echo 'var google_conversion_language = "en";';
echo 'var google_conversion_format = "3";';
echo 'var google_conversion_color = "ffffff";';
echo 'var google_conversion_label = "0yyZCMbm9mcQv9OKwwM";';
echo 'var google_remarketing_only = false;';
echo '/* ]]> */';
echo '</script>';
echo '<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">';
echo '</script>';
echo '<noscript>';
echo '<div style="display:inline;">';
echo '<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/945990079/?label=0yyZCMbm9mcQv9OKwwM&amp;guid=ON&amp;script=0"/>';
echo '</div>';
echo '</noscript>';
echo '<!-- Google Code for Remarketing Tag -->';
echo '<!--------------------------------------------------';
echo 'Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup';
echo '--------------------------------------------------->';
echo '<script type="text/javascript">';
echo '/* <![CDATA[ */';
echo 'var google_conversion_id = 942666675;';
echo 'var google_custom_params = window.google_tag_params;';
echo 'var google_remarketing_only = true;';
echo '/* ]]> */';
echo '</script>';
echo '</script>';
echo '<noscript>';
echo '<div style="display:inline;">';
echo '<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/942666675/?guid=ON&amp;script=0"/>';
echo '</div>';
echo '</noscript>';
echo '<style>[name="google_conversion_frame"]{position: absolute; z-index:0; bottom:0;}</style>';
echo '';
echo '<div itemscope itemtype="http://schema.org/Service" style="position: absolute; top: 0; opacity: 0;">';
echo '<span itemprop="name">babylon Dr App</span>';
echo '<div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">';
echo 'Rated <span itemprop="ratingValue">4.76</span>/5 based on <span itemprop="reviewCount">16,644</span> <a href="https://www.babylonhealth.com/reviews">customer reviews</a>';
echo '</div></div>';
echo '<script type="text/javascript">';
echo '_linkedin_data_partner_id = "21591";';
echo '</script><script type="text/javascript">';
echo '(function(){var s = document.getElementsByTagName("script")[0];';
echo 'var b = document.createElement("script");';
echo 'b.type = "text/javascript";b.async = true;';
echo 'b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";';
echo 's.parentNode.insertBefore(b, s);})();';
echo '</script>';
echo '<noscript>';
echo '<img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=21591&fmt=gif" />';
echo '</noscript>';
echo '<script>ga('linker:autoLink', ['online.babylonhealth.com', 'www.gpathand.nhs.co.uk'])</script>';
echo '';
echo '<header class="header" role="header">';
echo '<div class="container--full no-padding relative">';
echo '<button id="Burger" class="burger text-indent"> Menu';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '</button>';
echo '';
echo '<div class="logo">';
echo '<h1 class="no-margin">';
echo '<a class="logo__image text-indent" href="/" alt="Babylon Logo">';
echo '<img src="/assets/images/babylon-health-logo.svg" alt="Babylon health logo">';
echo '</a>';
echo '</h1>';
echo '</div>';
echo '';
echo '<nav id="NavigationMenu" class="navigation">';
echo '<ul id="NavigationMenuList" class="navigation__list">';
echo '<li class="navigation__list__item all-devices">';
echo '<a class="navigation__list__item__link" href="https://www.babylonhealth.com/how-it-works">Features</a>';
echo '</li>';
echo '<li class="navigation__list__item all-devices">';
echo '<a class="navigation__list__item__link" href="https://www.babylonhealth.com/about">About</a>';
echo '</li>';
echo '<li class="navigation__list__item all-devices">';
echo '<a class="navigation__list__item__link" href="https://www.babylonhealth.com/blog">Blog</a>';
echo '</li>';
echo '<li class="navigation__list__item all-devices">';
echo '<a';
echo 'class="navigation__list__item__link"';
echo 'href="https://www.gpathand.nhs.uk/">NHS</a>';
echo '</li>';
echo '<li class="navigation__list__item all-devices" id="ListSignInButton">';
echo '<a';
echo 'id="SignInButton"                class="navigation__list__item__link navigation__list__item__link--purple"';
echo 'href="https://babylon.onelink.me/4250792619?pid=Website_V2&amp;c=Homepage_NavBar_CTA&amp;af_dp=babylon%3A%2F%2F&amp;af_web_dp=https%3A%2F%2Fonline.babylonhealth.com%2Fsign-in">Sign in</a>';
echo '</li>';
echo '<li class="navigation__list__item all-devices item--cta">';
echo '<a class="button button--purple" href="/download-app">Download app</a>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</header>';
echo '';
echo '<main>';
echo '<style>';
echo '.header {';
echo 'background-color: transparent;';
echo 'box-shadow: none;';
echo 'position: absolute;';
echo '}';
echo '';
echo 'main {';
echo 'padding-top: 0;';
echo '}';
echo '';
echo '@media screen and (min-width: 600px) {';
echo 'padding-top: 5rem;';
echo '}';
echo '';
echo 'div[class*="QuestionRow-module__heart"] {';
echo 'opacity: 0;';
echo '}';
echo '';
echo '@media only screen and (max-width: 600px) {';
echo '#_hj_feedback_container {';
echo 'display: none;';
echo '}';
echo '';
echo 'div[class*="QuestionRow-module__heart"] {';
echo 'opacity: 0;';
echo '}';
echo '';
echo '.hero-chatbot__overlay--active div[class*="QuestionRow-module__heart"] {';
echo 'opacity: 1;';
echo '}';
echo '}';
echo '</style>';
echo '';
echo '<link href="https://chatbot-web-uk.babylonpartners.com/static/css/latest.css" rel="stylesheet" />';
echo '';
echo '<div class="hero-chatbot" style="background-image: url('/uploads/heros/babylon-runner-health.jpg');">';
echo '<div class="hero-chatbot__overlay">';
echo '<div class="hero-chatbot__container">';
echo '<div id="root"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script src="https://chatbot-web-uk.babylonpartners.com/config/app.config.js"></script>';
echo '<script src="https://chatbot-web-uk.babylonpartners.com/static/js/latest.js"></script>';
echo '<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyBaidgWQcYwa7cW0wmQUR32wpN-JeAxPlI&libraries=geometry,drawing,places"></script>';
echo '';
echo '<script type="text/javascript">';
echo 'var babylonIntroText = $('[class*=questionRow__text]').text()';
echo 'var maxHeight = $(window).height() - 150;';
echo 'var windowWidth = $(window).width();';
echo 'var hero = $('.hero-chatbot');';
echo 'var overlay = $('.hero-chatbot__overlay');';
echo 'var chatbotHeight = overlay.outerHeight();';
echo '';
echo 'var onResize = function(chatbotHeight, extraHeight) {';
echo 'extraHeight = extraHeight || 150;';
echo 'hero.css('min-height', chatbotHeight + extraHeight + 'px');';
echo '};';
echo '';
echo 'var adjustOverlayHeight = function() {';
echo 'if(windowWidth > 600) {';
echo '$('.hero-chatbot__container').css('max-height', maxHeight + 'px')';
echo '}';
echo 'onResize(chatbotHeight);';
echo '}';
echo '';
echo 'onResize(chatbotHeight, 150);';
echo '';
echo 'window.addEventListener('resize', function() {';
echo 'chatbotHeight = overlay.outerHeight();';
echo 'windowWidth = $(window).width();';
echo '';
echo 'if(windowWidth > 600) {';
echo 'onResize(chatbotHeight, 250);';
echo '} else {';
echo 'onResize(chatbotHeight, 0);';
echo '};';
echo '';
echo 'adjustOverlayHeight();';
echo '}, false);';
echo '';
echo 'document.getElementById('root').addEventListener('click', function (e) {';
echo 'chatbotHeight = overlay.outerHeight();';
echo 'if (e.target.attributes['data-e2e-type'] || e.target.attributes['data-e2e-handle']) {';
echo '$('.hero-chatbot__overlay')[0].classList.add('hero-chatbot__overlay--active');';
echo '$('html, body').animate({ scrollTop: 0 }, 'fast');';
echo 'adjustOverlayHeight();';
echo '}';
echo '})';
echo 'document.addEventListener('click', function (e) {';
echo 'if (/questionRow__backArrowButton/g.test(e.target.className) || /questionRow__exitButton/g.test(e.target.className)) {';
echo 'setTimeout(function () {';
echo 'chatbotHeight = overlay.outerHeight();';
echo 'if ($('[class*=questionRow__text]').text() === babylonIntroText) {';
echo '$('.hero-chatbot__overlay')[0].classList.remove('hero-chatbot__overlay--active')';
echo '$('.header').removeClass('header--white');';
echo '$('.hero-chatbot__container').css('max-height', '');';
echo 'onResize(chatbotHeight);';
echo '}';
echo '}, 100)';
echo '}';
echo '})';
echo 'document.getElementsByTagName('body')[0].classList.remove('is-mobile')';
echo '</script>';
echo '';
echo '<section class="section inline-images-slider" style="">';
echo '<div class="container--full ">';
echo '';
echo '<ul class="inline-images-slider__carousel grid grid-1" data-slider="carousel">';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/The-Huffington-Post-logo-04_161201_160723.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>&quot;A game changer in the world of on-demand healthcare&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/BBC-News-Logo-01.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>&quot;As easy as ordering a cab on your smartphone&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/The-Telegraph-logo-05.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>&quot;London startup babylon is building an artificially intelligent doctor&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Guardian-Logo-02.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>&quot;babylon fits with the idea that millennials now expect all their services to be streamlined&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Bupa-Logo-09.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>&quot;has the potential to change the way people access care&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Wired-Logo-06.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>“babylon puts an AI doctor in your pocket&quot;</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Raconteur-Logo-07.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>“For patients, this means remote check-ups, even in areas with relatively little healthcare provision”</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Aviva-Logo-08_161202_144658.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>“Healthcare has been calling out for this kind of innovation”</span>';
echo '</div>';
echo '</li>';
echo '<li class="inline-images-slider__carousel__item grid__3">';
echo '<div class="inline-images-slider__carousel__item__image">';
echo '<figure>';
echo '<img src="/uploads/home/Financial-Times-logo-03.png" alt="babylon carousel image">';
echo '</figure>';
echo '</div>';
echo '';
echo '<div class="inline-images-slider__carousel__item__description">';
echo '<span>“Set to secure new investment to develop a version powered by A.I.”</span>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</section>';
echo '<section class="section" style="">';
echo '<div class="container--full">';
echo '<div class="feature-two-column feature-two-column--reverse">';
echo '';
echo '<div class="feature-two-column__item item--left">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '<h2 style="color:#0099ff;">We’ve hand-picked the doctors</h2>';
echo '<p>Just 1 in 100 doctors make it through our tough hiring process, so you'll always get high quality healthcare wherever you are.</p>';
echo '<p>Make an appointment in seconds, see a doctor in minutes.</p>              </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="button standard" href="https://babylon.onelink.me/4250792619?pid=Website_V2&amp;c=Homepage_Other_CTA&amp;af_dp=babylon%3A%2F%2F&amp;af_web_dp=https%3A%2F%2Fonline.babylonhealth.com%2Fregister">Book a consultation</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class=" feature-two-column__item item--right">';
echo '<figure class="text-center  ">';
echo '<img src="/uploads/home/consultations-mobile-laptop-babylon-right.png" alt="Consultations Mobile Laptop Babylon Right">';
echo '</figure>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section" style="">';
echo '<div class="container">';
echo '<div class="feature-two-column">';
echo '';
echo '<div class="feature-two-column__item item--left">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '<h2 style="color:#9013fe;">And given them cutting edge technology</h2>';
echo '<p>Our doctors team-up with advanced artificial intelligence technology to give you the complete healthcare experience you deserve.</p>              </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="app-button--apple" href="https://itunes.apple.com/gb/app/babylon-health-doctor-consultations/id858558101?mt=8" data-type="apple">Apple Store</a>';
echo '<a class="app-button--google" href="https://play.google.com/store/apps/details?id=com.babylon&hl=en_GB" data-type="google">Google Play Store</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class=" feature-two-column__item item--right">';
echo '<figure class="text-center  ">';
echo '<img src="/uploads/home/babylon-phone-chat-bot.png" alt="Babylon Phone Chat Bot">';
echo '</figure>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section" style="">';
echo '<div class="container">';
echo '';
echo '<header class="container--narrow">';
echo '<div class="text-block text-center">';
echo '</div>';
echo '</header>';
echo '';
echo '<div class="features-dynamic-col">';
echo '<div class="container grid no-padding">';
echo '<div class="row grid-1">';
echo '<ul class="features-dynamic-col__list grid no-padding grid-list">';
echo '<li class="features-dynamic-col__list__item">';
echo '<figure class="features-dynamic-col__item__image">';
echo '<img src="/uploads/home/icon-speech-bubbles-babylon.svg" alt="Icon Speech Bubbles Babylon">';
echo '</figure>';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<h4>Taught by experts</h4>';
echo '<p>Our artificial intelligence technology is taught by our very own medical professionals, so you know you're always getting medical advice you can trust.</p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '<li class="features-dynamic-col__list__item">';
echo '<figure class="features-dynamic-col__item__image">';
echo '<img src="/uploads/home/icon-data-driven-babylon.svg" alt="Icon Data Driven Babylon">';
echo '</figure>';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<h4>Driven by data</h4>';
echo '<p>Your health data is continuously analysed and cross-referenced with other patients, giving you the right results whenever you need them.</p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<section class="section" style="">';
echo '<div class="container">';
echo '<div class="feature-two-column">';
echo '';
echo '<div class="feature-two-column__item item--left">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '<h2 style="color:#F8275A;">So you can get back on track, faster</h2>';
echo '<p>Once you're healthy, we'll keep you healthy.</p>';
echo '<p>babylon helps you track test results, activity levels and health info so you always have an up-to-date picture of how you’re doing.</p>              </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="app-button--apple" href="https://itunes.apple.com/gb/app/babylon-health-doctor-consultations/id858558101?mt=8" data-type="apple">Apple Store</a>';
echo '<a class="app-button--google" href="https://play.google.com/store/apps/details?id=com.babylon&hl=en_GB" data-type="google">Google Play Store</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class=" feature-two-column__item item--right">';
echo '<figure class="text-center  full-image  ">';
echo '<img src="/uploads/home/monitor_161101_164658.png" alt="Monitor 161101 164658">';
echo '</figure>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section text-center" style="color:#ffffff;background-image: url('/uploads/home/gradient-green-3.png');">';
echo '<div class="container--content-narrow  container--double-height">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '';
echo '<p>AVERAGE RATING 4.8 STARS</p>';
echo '<figure><img src="https://www.babylonhealth.com/uploads/home/Stars-ratings-white.svg" ;="" style="vertical-align: middle; cursor: pointer; max-width: 100%; height: auto;" data-pin-nopin="true"></figure>';
echo '<figure class="text-block__image"></figure>';
echo '<h4>We have more than 25,000 five star ratings and a 94% net promoter score</h4>';
echo '<p>Great relationships are built on trust and being able to listen. We take your feedback really seriously and act fast if members aren’t 100% happy. That’s why most our members give us 5 out of 5.</p>        </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="button button--white"  href="https://www.babylonhealth.com/reviews">Read our reviews</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section" style="">';
echo '<div class="container">';
echo '';
echo '<header class="container--narrow">';
echo '<div class="text-block text-center">';
echo '</div>';
echo '</header>';
echo '';
echo '<div class="features-dynamic-col">';
echo '<div class="container grid no-padding">';
echo '<div class="row grid-1">';
echo '<ul class="features-dynamic-col__list grid no-padding grid-list">';
echo '<li class="features-dynamic-col__list__item">';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<p><img src="/uploads/home/quotation-mark.svg" data-pin-nopin="true"></p>';
echo '<p>“Being able to choose when I speak to a GP is so much more convenient than taking time off work and spending hours in waiting rooms. The app is very slick and I like the UI.”</p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '<li class="features-dynamic-col__list__item">';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<p><img src="/uploads/home/quotation-mark.svg"></p>';
echo '<p>“Downloaded the app one Saturday, asked a few questions, booked a video appointment and that same evening I was seen by a very nice GP. Genius.”</p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '<li class="features-dynamic-col__list__item">';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<p><img src="/uploads/home/quotation-mark.svg" data-pin-nopin="true"></p>';
echo '<p>“I used babylon from LA today. The doctor confirmed I was ok to wait until I got back to the UK. Instantly put my mind at rest and saved me the admin of insurance in the US! Fantastic.”</p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<section class="section" style="">';
echo '<div class="container container--double-height">';
echo '';
echo '<header class="container--narrow">';
echo '<div class="text-block text-center">';
echo '<div class="text-block__content">';
echo '<h2 style="color:#0099ff;">Our badges of honour</h2>';
echo '<p class="narrow">The people at BSI and CQC are pretty tough to please, but we’re pleased to say they’ve both rubber stamped our high standards of service.</p>          </div>';
echo '</div>';
echo '</header>';
echo '';
echo '<div class="features-dynamic-col">';
echo '<div class="container grid no-padding">';
echo '<div class="row grid-1">';
echo '<ul class="features-dynamic-col__list grid no-padding grid-list">';
echo '<li class="features-dynamic-col__list__item">';
echo '<figure class="features-dynamic-col__item__image">';
echo '<img src="/uploads/home/CQC-babylonhealth.svg" alt="Cqc Babylonhealth">';
echo '</figure>';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<h4 style="color:#0099ff;">Quality care, always</h4>';
echo '<p>We passed our Care Quality Commission inspection with flying colours. <a href="http://www.cqc.org.uk/location/1-2827110122?referer=widget3#accordion-1" target="_blank">View CQC report</a></p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '<li class="features-dynamic-col__list__item">';
echo '<figure class="features-dynamic-col__item__image">';
echo '<img src="/uploads/home/BSI-ISO-babylonhealth.svg" alt="Bsi Iso Babylonhealth">';
echo '</figure>';
echo '';
echo '<div class="text-block">';
echo '<div class="text-block__content--small">';
echo '<h4 style="color:#0099ff;">Your data, safe in our hands</h4>';
echo '<p>We’re BSI certified: ISO 27001 under certificate number IS 640036. <a href="https://www.bsigroup.com/en-GB/our-services/certification/certificate-and-client-directory/search-results/?searchkey=licence%3d640036&licencenumber=IS%20640036" target="_blank">View certificate</a></p>                    </div>';
echo '';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<section class="section" style="color:#ffffff;background-color:#192750;background-size:cover;">';
echo '<div class="container--full">';
echo '<div class="feature-two-column feature-two-column--reverse">';
echo '';
echo '<div class="feature-two-column__item item--left">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '<h2>But don’t just take our word for it</h2>';
echo '<p>babylon has won some pretty prestigious industry awards, so you know we’ve been patted on the back by people who know what they’re talking about.</p>              </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="button button--white" href="/awards">Learn more</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class=" feature-two-column__item item--right">';
echo '<figure class="text-center  ">';
echo '<img src="/uploads/home/babylon-award-logos-white.png" alt="Babylon Award Logos White">';
echo '</figure>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="section text-center" style="color:#ffffff;background-color:#8139FF;background-size:cover;">';
echo '<div class="container  container--double-height">';
echo '<div class="text-block">';
echo '<div class="text-block__content">';
echo '';
echo '<h3>So what are you waiting for?</h3>';
echo '<p>Download babylon to your phone, or register online, from anywhere in the world.</p>        </div>';
echo '';
echo '<div class="text-block__action">';
echo '<a class="app-button--apple" href="https://itunes.apple.com/gb/app/babylon-health-doctor-consultations/id858558101?mt=8" data-type="apple">Apple Store</a>';
echo '<a class="app-button--google" href="https://play.google.com/store/apps/details?id=com.babylon&hl=en_GB" data-type="google">Google Play Store</a>';
echo '<a class="app-button--web" href="https://online.babylonhealth.com/sign-in" data-type="desktop">Website</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '</main>';
echo '';
echo '<footer class="footer" role="footer">';
echo '<div class="footer__top container no-padding grid">';
echo '<div class="grid__4">';
echo '<ul class="footer__column">';
echo '<li class="column__item column__item__title title">';
echo '<h3>Learn more</h3>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/careers">Careers</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/for-doctors">For Doctors</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/press/press-centre">Press centre</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/news/">babylon in the news</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="/what-we-treat">What we treat</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://support.babylonhealth.com/">FAQs</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="/contact">Contact us</a>';
echo '</li>';
echo '</ul>';
echo '</div><!-- end of first footer column -->';
echo '<div class="grid__4">';
echo '<ul class="footer__column">';
echo '<li class="column__item column__item__title title">';
echo '<h3>Partner with us</h3>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/business">Business</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/partnerships">Partnerships</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/international">International</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://www.babylonhealth.com/for-pharmacies">For pharmacies</a>';
echo '</li>';
echo '</ul>';
echo '</div><!-- end of second footer column -->';
echo '<div class="grid__4">';
echo '<ul class="footer__column">';
echo '<li class="column__item column__item__title title">';
echo '<h3>Get in touch</h3>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="mailto:support@babylonhealth.com">support@babylonhealth.com</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<span class="column__item__subtitle">Clinical support:</span>';
echo '<a href="tel:004403302231008">UK: +44 (0) 33 0223 1008</a>';
echo '<a href="tel:00353212355755">Ireland: +353 (21) 2355 755</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<span class="column__item__subtitle">General:</span>';
echo '<a href="tel:004402071000762"> +44 (0) 20 7100 0762</a>';
echo '</li>';
echo '</ul>';
echo '</div><!-- end of third footer column -->';
echo '<div class="grid__4">';
echo '<ul class="footer__column">';
echo '<li class="column__item column__item__title title">';
echo '<h3>Follow us</h3>';
echo '</li>';
echo '<li>';
echo '<ul class="column__item--socialList">';
echo '<li class="column socialList__item grid__4">';
echo '<a class="socialList__item__facebook text-indent" href="https://www.facebook.com/babylon-health-273632119481099/?fref=ts" target="_blank" aria-lable="Icon Facebook">Facebook</a>';
echo '</li>';
echo '<li class="column socialList__item grid__4">';
echo '<a class="socialList__item__twitter text-indent" href="https://twitter.com/babylonhealth" target="_blank" aria-lable="Icon Twitter">Twitter</a>';
echo '</li>';
echo '<li class="column socialList__item grid__4">';
echo '<a class="socialList__item__instagram text-indent" href="https://www.instagram.com/babylonhealth/" target="_blank" aria-lable="Icon Instagram">Instagram</a>';
echo '</li>';
echo '<li class="column socialList__item grid__4">';
echo '<a class="socialList__item__linkedin text-indent" href="https://www.linkedin.com/company/babylonhealth" target="_blank" aria-lable="Icon LinkedIn">LinkedIn</a>';
echo '</li>';
echo '</ul>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="/blog">Blog</a>';
echo '</li>';
echo '<li class="column__item">';
echo '<a href="https://blog.babylonhealth.com/">Tech blog</a>';
echo '</li>';
echo '</ul>';
echo '</div><!-- end of fourth footer column -->';
echo '</div><!-- end of .footer__top -->';
echo '';
echo '<div class="footer__bottom container no-padding">';
echo '<ul class="footer__bottom__copyright">';
echo '<li class="footer__bottom__copyright__item">&copy; babylon 2018 - All rights reserved</li>';
echo '<li class="footer__bottom__copyright__item">60 Sloane Avenue, London SW3 3DD</li>';
echo '<li class="footer__bottom__copyright__item item__link">';
echo '<a href="/terms">Terms &amp; Conditions</a>';
echo '</li>';
echo '<li class="footer__bottom__copyright__item item__link">';
echo '<a href="/terms/privacy">Privacy Policy</a>';
echo '</li>';
echo '<li class="footer__bottom__copyright__item item__link">';
echo '<a href="/terms/cookies">Cookies</a>';
echo '</li>';
echo '</ul>';
echo '</div><!-- end of .footer__bottom -->';
echo '</footer><!-- end of .footer -->';
echo '</body>';
echo '</html>';
echo '';
?>